@startuml Institution Determination

WebClient -> IMPClient: Transmit QR-Code (camera scan)
IMPClient -> IMPServer: Request Content of Request Template
IMPServer --> IMPClient: Send Request Template
IMPClient -> IMPClient: Display Request
IMPClient -> IMPClient: Automated Filling of Attributes 
User -> IMPClient: Fill in Missing Attributes
User -> IMPClient: Approve Request
IMPClient --> IMPServer: Send Approve Request
IMPClient --> IMPServer: Request ID, User IMP ID, Personal Information
IMPServer -> PortalConnector: Request Approval
IMPServer -> PortalConnector: Request ID, User IMP ID, Personal Information
PortalConnector -> Portal: Request Determination of Responsible Institution
Portal -> Portal: Determine Responsible Institution
Portal --> PortalConnector: Send Responsible Institution

@enduml
