@startuml Institution Request

Institution -> InstitutionConnector: Request to Send Request to IMP-ID
Institution -> InstitutionConnector: FIM-ID, User IMP-ID
InstitutionConnector -> FIMRepository: Request Data Field Schemata of FIM-ID
FIMRepository --> InstitutionConnector: Send Data Field Schemata
InstitutionConnector -> InstitutionConnector: Map Data Field Schemata to IMP Attributes
InstitutionConnector -> IMPServer: Request to Initiate Request Template
InstitutionConnector -> IMPServer: Send Template Content
IMPServer -> IMPServer: Initiate Request Template

note left
Template Content:
Type: Attribute Access Request
Issuer: Institution IMP ID
Reason: FIM-ID
Requested Attributes: ...
Response Address: IMPServer
Template ID: ...
end note

IMPServer --> InstitutionConnector: Send Request Template ID
InstitutionConnector -> IMPServer: Send Request Template ID to IMP-ID
IMPServer -> IMPClient: Send Request Template ID
IMPClient -> IMPServer: Request Request Template Content
IMPServer --> IMPClient: Send Request Template Content
IMPClient -> IMPClient: Display Request
IMPClient -> IMPClient: Automatically fill Attributes
User -> IMPClient: Fill in Missing Attributes
User -> IMPClient: Approve Request
IMPClient -> IMPServer: Send Approve Request
IMPClient -> IMPServer: Request ID, User IMP ID, Personal Information
IMPServer -> InstitutionConnector: Request Approval
IMPServer -> InstitutionConnector: Request ID, User IMP ID, Personal Information
InstitutionConnector -> InstitutionConnector: Map IMP Attributes to Data Field Schemata
InstitutionConnector -> Institution: Submit Application
Institution -> Institution: Process Application

@enduml