@startuml

class Portal {
    {method} - getWebsite(URL): Website
    {method} - searchServiceWebsiteURL(SearchTerm): [URL]

}

class PortalConnector {
    {field} - IMP-ID
    {method} - getNewRequestTemplateQRCode(RequestTemplateParameter): QR-Code
    {method} - getExistingRequestTemplateQRCode(FIM-ID): QR-Code
    {method} - getRequestTemplateParameter(FIM-ID): RequestTemplateParameter
    {method} - sendRequestResponse(RequestID, response)
}

PortalConnector "1" -- "many" RequestTemplateParameter
PortalConnector "1" --> "1" IMPServer: <<uses>>

class RequestTemplateParameter {
    {field} - FIM-ID
    {field} - Portal IMP-ID
    {field} - Reason
    {field} - Type
    {field} - Requested Attributes
}

PortalConnector "1" -- "many" RequestTemplateQRCode

class RequestTemplateQRCode {
    {field} - FIM-ID: QR-Code
}

Portal "1" -- "many" Website: hosts
Portal "1" -- "1" PortalConnector

class Website {
    {field} - URL
}

Website <|-- ServiceWebsite: instance
Website <|-- Homepage: instance

class Homepage {
    {method} - getServiceWebsiteURL(SearchTerm): [URL]
}

Homepage --> Portal: <<uses>>

class ServiceWebsite {
    {field} - FIM-ID
    {method} - getRequestTemplateQRCode(FIM-ID)
}

ServiceWebsite --> PortalConnector: <<uses>>


class IMPClient {
    {field} - IMP-ID
    {field} - Personal Information
    {method} - scanQRCode(ServiceWebsite): RequestTemplateID
    {method} - getRequestTemplate(RequestTemplateID): RequestTemplate
    {method} - displayRequestTemplate(RequestTemplate)
    {method} - fillInRequestTemplate(RequestTemplate)
    {method} - sendRequestTemplateResponse(RequestTemplateID, Response, IMP-ID, Attributes)
    {method} - getRequest(RequestID): Request
}

IMPClient --> ServiceWebsite: <<uses>>

IMPClient --> IMPServer: <<uses>>


class IMPServer {
    {field} - IMPServerAddress
    {method} - initializeRequestTemplate(RequestTemplateParameters): RequestTemplateID
    {method} - sendRequestTemplate(RequestTemplate)
    {method} - createQRCode(RequestTemplateID): QR-Code
    {method} - sendQRCode(QR-Code)
    {method} - initializeRequest(RequestTemplateID, IMP-ID): Request
    {method} - updateRequestStatus(status)
    {method} - sendRequest(IMP-ID, RequestID)
    {method} - notifyRequestUpdate(IMP-ID, RequestID)
}

IMPServer "1" -- "many" Request

class Request {
    {field} RequestID
    {field} RequestTemplateID
    {field} IMP-ID
    {field} Status
    {field} Attributes
}

IMPServer "1" -- "many" RequestTemplate

class RequestTemplate {
    {field} - RequestTemplateID
    {field} - RequestTemplateType
    {field} - RequestTemplateIssuer
}

RequestTemplate <|-- AttributeRequestTemplate: instance

class AttributeRequestTemplate {
    {field} - RequestedAttributes
}


@enduml