@startuml

Webclient -> Portal: getWebsite(HomePage)
Portal --> Webclient: HomePage
Webclient -> Portal: getServiceWebsiteURL(SearchTerm)
Portal -> Portal: searchServiceWebsiteURL(SearchTerm)
Portal --> Webclient: [URL]
User -> Webclient: Choose URL
Webclient -> Portal: getWebsite(URL)
Portal --> Webclient: ServiceWebsite


Webclient -> PortalConnector: getRequestTemplateQRCode(FIM-ID)
PortalConnector -> PortalConnector: getRequestTemplateParameter(FIM-ID): RequestTemplateParameter
PortalConnector -> IMPServer: getNewRequestTemplateQRCode(RequestTemplateParameter)
IMPServer -> IMPServer: initializeRequestTemplate(RequestTemplateParameters): RequestTemplateID
IMPServer -> IMPServer: createQRCode(RequestTemplateID): QR-Code
IMPServer --> PortalConnector: sendQRCode(QR-Code)
PortalConnector --> Webclient: QR-Code


IMPClient -> Webclient: scanQRCode(ServiceWebsite): RequestTemplateID
IMPClient -> IMPServer: getRequestTemplate(RequestTemplateID)
IMPServer --> IMPClient: RequestTemplate
IMPClient -> IMPClient: fillInRequestTemplate(RequestTemplate)
IMPClient -> IMPClient: displayRequestTemplate(RequestTemplate)
User -> IMPClient: Fill in Attributes
User -> IMPClient: Approve Request

IMPClient -> IMPServer: sendRequestTemplateResponse(RequestTemplateID, Response, IMP-ID, Attributes)
IMPServer -> IMPServer: initializeRequest(RequestTemplateID, IMP-ID): Request
IMPServer -> PortalConnector: sendRequest(IMP-ID, RequestID)
PortalConnector -> IMPServer: sendRequestResponse(RequestID, response)

IMPServer -> IMPClient: notifyRequestUpdate(IMP-ID, RequestID)
IMPClient -> IMPServer: getRequest(RequestID)
IMPServer --> IMPClient: Request

@enduml