@startuml Basic Use Case

group Selection Administrative Service

WebClient -> Portal: Request HomePage
Portal --> WebClient: HomePage
WebClient -> Portal: Search for Service
Portal --> WebClient: List of Services
WebClient -> WebClient: Select Service
WebClient -> Portal: Request Webpage of Service
Portal --> WebClient: Webpage of Service

end

WebClient -> IMPClient: Transfer QR Code (camera scan) which includes IMP ID of portal and ID of administrative service
IMPClient -> IMPClient: Ask permission to share location with reason: Determination of Institution
IMPClient --> PortalConnector: Share location
PortalConnector -> Portal: Request to determine responsible institution
Portal -> Portal: Determine responsible institution
Portal --> PortalConnector: Responsible institution
PortalConnector -> DataExchangePlatform: Request to submit "empty" application to instituion along with IMP ID of user
DataExchangePlatform -> InstitutionConnector: Transfer empty application along with IMP ID
InstitutionConnector -> IMPClient: Initiate relationship
IMPClient -> IMPClient: Request user to approve relationship
IMPClient --> InstitutionConnector: Accept relationship
InstitutionConnector -> IMPClient: Initiate authorisation request for attributes with reason: application for administration service XY
IMPClient -> IMPClient: Ask permission to authorize institution to read personal information
IMPClient -> FIMRepository: Request Data Field Schemata of FIM-ID
FIMRepository --> IMPClient: Send Data Field Schemata
IMPClient -> IMPClient: Present interactive form to user
IMPClient --> InstitutionConnector: Accept authorisation request and submit personal information
InstitutionConnector -> Institution: Submit application
Institution -> Institution: Process application
Institution --> InstitutionConnector: Submit result of application
InstitutionConnector --> IMPClient: Transfer result of application
IMPClient -> IMPClient: Display application result

@enduml