@startuml Notify Institution

PortalConnector -> Portal: Request to Submit Application
PortalConnector -> Portal: FIM-ID, User IMP-ID
Portal -> DataExchangePlatform: Request to Deliver Application
Portal -> DataExchangePlatform: FIM-ID, User IMP-ID
DataExchangePlatform -> Institution: Transmit Application
DataExchangePlatform -> Institution: FIM-ID, User IMP-ID

@enduml